#!/bin/python3
import os
import sys
from libretranslatepy import LibreTranslateAPI

lt = LibreTranslateAPI("https://libretranslate.de/")

path = os.path.dirname(os.path.abspath(__file__))
with open(path+"/words.csv", "r") as f:
    lines = f.readlines()

def find(query, lang="auto"):
    matches = []
    if lang == "ru":
        for line in lines:
            word, translation, example = line.split(",")[:3]
            if query == word.split(" ")[0]:
                matches.append(word+" = "+translation+" ---> "+example)
    if not matches:
        matches.append("Local translation not found, using libtranslate api")
        matches.append(query+" = "+lt.translate(query, lang, "en"))
    return matches

if len(sys.argv) > 1:
    if len(sys.argv) == 2:
        lang = "ru"
        query = sys.argv[1]
    if len(sys.argv) == 3:
        lang = sys.argv[1]
        query = sys.argv[2]
    matches = find(query, lang)
    print(f"Results for '{query}'\n")
    for match in matches:
        print(match)
    print("\n")
else:
    while True:
        query = input("word: ")
        if query == "":
            continue
        matches = find(query, ru)
        print(f"Results for '{query}'\n")
        for match in matches:
            print(match)
        print("\n")
